### ISSUE TITLE
关于inference

### ISSUE THREAD

**Issue by LinyeLi60** [huanyuhello/CoDiNet#2]
您提到动态 网络的 选择机制： train：执行 或不执行 同时进行，并对两者进行加权。 test：根据sample adaptive 的权值，进行二值化。但是您提供的代码中test阶段并没有根据sample adaptive 的权值，进行二值化的结果选择当前block是否执行，这样如何达到加速推理的效果呢？我测试了gate的推理时间，和block的推理时间，虽然gate的只有block4%的计算量，但是gate和block的推理时间是接近的，这样无法达到加速推理的效果！

**Comment by huanyuhello** [comment]
1. 在当前 的代码版本中，是没有进行加速的。 因为方便起见， 在inference 的过程同样是 执行了block。 
2. 在实际的应用中，您可以简单的通过 if gate == 1：执行； else: 跳过。  改变代码的 执行流。 
3. 您测试的 单纯 gate 推理时间 和 单纯 block 推理时间是相同的吗？

**Comment by LinyeLi60** [comment]
我的测试显卡为RTX3080ti，cuda11.1
测试数据集：cifar10
首先测试原生的resnet110模型，推理平均时间18ms一张图片， flops:  254984832.0 params:  1727962.0
然后测试执行所有的gate和block，推理平均时间50ms一张图片，flops:  255368416.0 params:  1829654.0
从这里可以看出gate的参数量和flops虽然很少，但是gate全连接的模型结构导致推理时间占用很多，这样如何达到加速目的呢？

**Comment by huanyuhello** [comment]
您测试的过程里有两个问题， 1：flops 计算过程中，当前实现版本里面 不论 是否跳过，都进行了 执行。也就是说  flops: 255368416.0 这个是含有 所有gate 和 block 的计算量。是理论上的最大值。如果加速，需要 通过 if gate == 1：执行 block； else: 跳过block 。 这样 计算量是 所有gate 的计算量 +  执行的block。  2. gate 计算量 = Hin × Win x Cin。 Block 计算量 = K × K × Cin × Hout × Wout × Cout

**Comment by huanyuhello** [comment]
上述 计算量 公式 是 fc 与 conv 的，并非 gate 与 block 。 ps： 原理一样

**Comment by huanyuhello** [comment]
![image](https://user-images.githubusercontent.com/8136946/128300767-b977fa2c-06e8-4550-ae2d-5cd3c06d1603.png)
测试代码如上. 

1 cifar10 / Basicblock (s): 

ga: 0.00019598007202148438
bl: 0.0003871917724609375
ga: 0.00016736984252929688
bl: 0.0002838207244873047
ga: 0.00014819374084472656
bl: 0.000301361083984375
ga: 0.00018668174743652344
bl: 0.00028252601623535156
ga: 0.00015616416931152344
bl: 0.0001811981201171875
ga: 0.00025773048400878906
bl: 0.00032019615173339844
ga: 0.00024700164794921875
bl: 0.0003025531768798828
ga: 0.00015497207641601562
bl: 0.00017762184143066406
ga: 0.00018858909606933594
bl: 0.00023102760314941406


2. ImageNet / BottleNeck (s)
bl: 0.0030014514923095703
ga: 0.00041174888610839844
bl: 0.002811908721923828
ga: 0.00031065940856933594
bl: 0.0024657249450683594
ga: 0.0003676414489746094
bl: 0.0021660327911376953
ga: 0.0004291534423828125
bl: 0.002285480499267578
ga: 0.0004737377166748047
bl: 0.0028688907623291016
ga: 0.0005021095275878906
bl: 0.0025784969329833984
ga: 0.00036334991455078125
bl: 0.0024030208587646484
ga: 0.0005021095275878906
bl: 0.0023453235626220703
ga: 0.0013799667358398438
bl: 0.0031511783599853516
ga: 0.0014770030975341797
bl: 0.0030236244201660156
ga: 0.0008966922760009766
bl: 0.0047681331634521484
ga: 0.000888824462890625
bl: 0.005043745040893555
ga: 0.0006358623504638672
